database:
  external:
    driver: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://postgresql:5432/hive
    user: postgres
  type: external

expose:
  type: clusterIp

image:
  repository: harbor.starburstdata.net/starburstdata/hive

nodeSelector:
  starburstpool: base

objectStorage:
  gs:
    cloudKeyFileSecret: service-account-key

registryCredentials:
  enabled: true
  registry: harbor.starburstdata.net/starburstdata
