fullnameOverride: postgresql

global:
  postgresql:
    postgresqlDatabase: postgres
    postgresqlUsername: postgres
    servicePort: 5432

image:
  tag: 13

initdbScripts:
  init.sql: create database hive; create database ranger; create database insights; create database datacache;

primary:
  nodeSelector:
    starburstpool: base

readReplicas:
  nodeSelector:
    starburstpool: base

service:
  type: ClusterIP
